name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: fugue-project/.common/.github/workflows/pypi-publish.yml@main
